"""Dependency-free foundations for the mouse simulation data model."""

from .canonical import (
    cache_key,
    cache_key_for_manifest,
    canonical_bytes,
    canonical_json,
    canonical_value,
    content_hash,
    entity_content_hash,
    hashed_entity,
    make_cache_key,
    manifest_hash,
    sha256_bytes,
    sha256_content,
    sha256_file,
    without_identity,
)
from .errors import (
    CanonicalizationError,
    DocumentValidationError,
    MouseSimError,
    ReferenceError,
    SerializationError,
    UnitError,
    UnsupportedVersionError,
    ValidationError,
)
from . import model as _model
from .model import *
from .schema import (
    SCHEMA_PATH,
    deserialize,
    document_from_dict,
    document_to_dict,
    document_validation_errors,
    load_schema,
    schema_path,
    serialize,
    validate,
    validate_document,
    validate_references,
)
from .units import (
    UNIT_SPECS,
    UnitSpec,
    convert,
    from_si,
    normalize_unit,
    normalize_value,
    si_unit_for_dimension,
    to_si,
    unit_dimension,
    unit_spec,
)
from .geometry import (
    AABB,
    Bounds,
    Box,
    Compound,
    Cone,
    Cylinder,
    Frustum,
    GeometricProperties,
    Geometry,
    MeshDiagnostics,
    Mesh,
    RigidTransform,
    Sphere,
    Tensor3,
    Transform,
    TriangleMesh,
    closed_mesh_diagnostics,
    geometry_from_dict,
)
from .importers import GeometryLoadResult, ImportDiagnostic, load_geometry
from .mass import MassPropertiesResult, ObjectMassProperties, mass_properties
from .classification import ClassificationResult, ObjectClassification, classify_objects
from .qualification import (
    GATE_SPECS,
    QualificationGate,
    QualificationResult,
    evaluate_qualification,
    impact_qualification_status,
    method_supports,
)
from .validation import (
    ValidationFinding,
    ValidationReport,
    check_classification,
    check_geometry_health,
    check_material,
    check_pcb_clearance,
    check_wall_thickness,
    run_validation,
)


__all__ = list(
    set(
        list(_model.__all__)
        + [
            "cache_key",
            "cache_key_for_manifest",
            "canonical_bytes",
            "canonical_json",
            "canonical_value",
            "content_hash",
            "entity_content_hash",
            "hashed_entity",
            "make_cache_key",
            "manifest_hash",
            "sha256_bytes",
            "sha256_content",
            "sha256_file",
            "without_identity",
            "CanonicalizationError",
            "DocumentValidationError",
            "MouseSimError",
            "ReferenceError",
            "SerializationError",
            "UnitError",
            "UnsupportedVersionError",
            "ValidationError",
            "SCHEMA_PATH",
            "deserialize",
            "document_from_dict",
            "document_to_dict",
            "document_validation_errors",
            "load_schema",
            "schema_path",
            "serialize",
            "validate",
            "validate_document",
            "validate_references",
            "UNIT_SPECS",
            "UnitSpec",
            "convert",
            "from_si",
            "normalize_unit",
            "normalize_value",
            "si_unit_for_dimension",
            "to_si",
            "unit_dimension",
            "unit_spec",
            "Bounds",
            "AABB",
            "Box",
            "Compound",
            "Cone",
            "Cylinder",
            "Frustum",
            "GeometricProperties",
            "Geometry",
            "MeshDiagnostics",
            "Mesh",
            "RigidTransform",
            "Sphere",
            "Tensor3",
            "Transform",
            "TriangleMesh",
            "closed_mesh_diagnostics",
            "geometry_from_dict",
            "GeometryLoadResult",
            "ImportDiagnostic",
            "load_geometry",
            "MassPropertiesResult",
            "ObjectMassProperties",
            "mass_properties",
            "ClassificationResult",
            "ObjectClassification",
            "classify_objects",
            "GATE_SPECS",
            "QualificationGate",
            "QualificationResult",
            "evaluate_qualification",
            "impact_qualification_status",
            "method_supports",
            "ValidationFinding",
            "ValidationReport",
            "check_classification",
            "check_geometry_health",
            "check_material",
            "check_pcb_clearance",
            "check_wall_thickness",
            "run_validation",
        ]
    )
)

from .collision import (
    CLEARANCE_NOT_CERTIFIED,
    PAIR_RULE_APPLIED,
    STACKUP_CONSUMED_GAP,
    TOLERANCE_APPLIED,
    STATUS_CLEAR,
    STATUS_CONTACT,
    STATUS_ESTIMATE,
    STATUS_INTERFERENCE,
    STATUS_UNKNOWN,
    ClearanceResult,
    clamp,
    clearance_between,
    pair_clearance_matrix,
    sign,
)

__all__ += [
    "CLEARANCE_NOT_CERTIFIED",
    "PAIR_RULE_APPLIED",
    "STACKUP_CONSUMED_GAP",
    "TOLERANCE_APPLIED",
    "STATUS_CLEAR",
    "STATUS_CONTACT",
    "STATUS_ESTIMATE",
    "STATUS_INTERFERENCE",
    "STATUS_UNKNOWN",
    "ClearanceResult",
    "clamp",
    "clearance_between",
    "pair_clearance_matrix",
    "sign",
]

from .impact import (
    CONTACT_PATCH_ASSUMPTION,
    DESK_EDGE_CONTACT_APPROXIMATION,
    FATIGUE_ESTIMATE_EXCEEDED,
    IMPACT_UNSUPPORTED_FAILURE_MODES,
    ImpactResult,
    UNSUPPORTED_BATTERY_CRUSH,
    UNSUPPORTED_DELAMINATION,
    UNSUPPORTED_FRACTURE,
    UNSUPPORTED_PCB_SHOCK,
    UNSUPPORTED_SCREW_PULLOUT,
    desk_edge_impact,
    estimate_impact,
    repeat_impact_cycles,
)

__all__ += [
    "CONTACT_PATCH_ASSUMPTION",
    "DESK_EDGE_CONTACT_APPROXIMATION",
    "FATIGUE_ESTIMATE_EXCEEDED",
    "IMPACT_UNSUPPORTED_FAILURE_MODES",
    "ImpactResult",
    "UNSUPPORTED_BATTERY_CRUSH",
    "UNSUPPORTED_DELAMINATION",
    "UNSUPPORTED_FRACTURE",
    "UNSUPPORTED_PCB_SHOCK",
    "UNSUPPORTED_SCREW_PULLOUT",
    "desk_edge_impact",
    "estimate_impact",
    "repeat_impact_cycles",
]

from .physics import (
    BEAM_METHOD,
    BEAM_UNSUPPORTED_FAILURE_MODES,
    CLOSED_FORM_METHOD,
    MOUSE_LOAD_TEMPLATES,
    POINT_LOAD_SINGULARITY,
    SERIES_NOT_CONVERGED,
    SHELL_PANEL_ASSUMPTIONS,
    SHELL_PANEL_METHOD,
    SHELL_UNSUPPORTED_FAILURE_MODES,
    SOLVER_CAPABILITIES,
    SolverCapabilities,
    StructuralResponse,
    THIN_SHELL_OUT_OF_RANGE,
    UNDERCONSTRAINED_REACTIONS,
    UNSUPPORTED_STIFFNESS_REDUCTION,
    beam_response,
    preflight_structural_case,
    shell_panel_response,
    solve_load_case,
)

__all__ += [
    "BEAM_METHOD",
    "BEAM_UNSUPPORTED_FAILURE_MODES",
    "CLOSED_FORM_METHOD",
    "MOUSE_LOAD_TEMPLATES",
    "POINT_LOAD_SINGULARITY",
    "SERIES_NOT_CONVERGED",
    "SHELL_PANEL_ASSUMPTIONS",
    "SHELL_PANEL_METHOD",
    "SHELL_UNSUPPORTED_FAILURE_MODES",
    "SOLVER_CAPABILITIES",
    "SolverCapabilities",
    "StructuralResponse",
    "THIN_SHELL_OUT_OF_RANGE",
    "UNDERCONSTRAINED_REACTIONS",
    "UNSUPPORTED_STIFFNESS_REDUCTION",
    "beam_response",
    "preflight_structural_case",
    "shell_panel_response",
    "solve_load_case",
]

from .reports import (
    EVIDENCE_SCHEMA_ID,
    REPORT_SCHEMA_ID,
    render_evidence_package,
    render_html_report,
    render_json_report,
)

__all__ += [
    "EVIDENCE_SCHEMA_ID",
    "REPORT_SCHEMA_ID",
    "render_evidence_package",
    "render_html_report",
    "render_json_report",
]
